exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytype",
    "node_modules",
    ".svn",
    ".tox",
    "__pypackages__",
    "_build",
    "buck-out",
    "venv",
    "site-packages",

    ".cache",
    "**/__pycache__",
    ".devcontainer",
    ".pytest_cache",
    ".venv",
    ".vscode",
    "datasets",
    "drawio",
    ".ipynb_checkpoints",
    ".ruff_cache",
    "build",
    "dist",
]
line-length = 150 # Ensure this matches your desired line length
indent-width = 4

[lint]
select = ["E", "W", "F", "NPY", "I", "N", "RET", "Q", "PT"]
fixable = ["ALL"]
ignore = []                                                 # Ensure E501 is included in the fixable list

[format]
docstring-code-format = false
docstring-code-line-length = 88   # Set this to match the line-length
exclude = []
indent-style = "space"
line-ending = "auto"
preview = false
quote-style = "double"
skip-magic-trailing-comma = false
